default_language_version:
  python: python3.14
fail_fast: false
minimum_pre_commit_version: 4.1.0
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
    exclude: ^\.github/ISSUE_TEMPLATE/
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict
  - id: detect-private-key
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - args:
    - --fix
    id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
- hooks:
  - id: python-print-detection
  - id: python-pprint-detection
  - id: python-unreachable-code
  - id: yaml-sorter
    exclude: ^(\.github/ISSUE_TEMPLATE/|\.github/workflows/|\.pre-commit-config\.yaml)
  repo: https://github.com/chrysa/pre-commit-tools
  rev: v0.1.1-58
