sonar.projectKey=chrysa_epub-sorter
sonar.organization=chrysa
sonar.projectName=epub-sorter
sonar.sources=.
sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**,**/dist/**,**/build/**
