on:
  push:
    branches:
    - main
    paths:
    - '**.py'
  workflow_dispatch: null
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - name: Build with pyinstaller
      run: 'pyinstaller --onefile --noconsole main.py --name "epub-sorter"

        '
    - uses: actions/upload-artifact@v7
      with:
        name: e_opub_order_windows
        path: .\dist\e_opub_order.exe
    strategy:
      matrix:
        python-version:
        - 3.1
  create-release:
    needs:
    - build-on-windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8
      with:
        path: ./
    - env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      id: create_release
      name: Create github release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: Release Version ${{ github.run_number }}
        tag_name: v${{ github.run_number }}
    - env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      name: Upload windows artifact to github release
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application
        asset_name: e_opub_order_windows.exe
        asset_path: ./epub-sorter*epub-sorter.exe
        upload_url: ${{ steps.create_release.outputs.upload_url }}
name: build exe and release
